[package]
name = "monsters"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
common = { path = "../common" }
assets = { path = "../assets" }
serde = { version = "1.0", features = ["derive"] }
bevy_common_assets = { version = "0.14", features = ["ron"] }
