# Add support for faster linkers
# [target.x86_64-unknown-linux-gnu]
# linker = "clang"
# rustflags = ["-C", "link-arg=-fuse-ld=mold"]

# [target.x86_64-pc-windows-msvc]
# linker = "rust-lld.exe"

# Generic optimization for dependencies
[profile.dev.package."*"]
opt-level = 3
